# Schema for the configuration files of the simple mailchimp module.
simple_mailchimp.settings:
  type: config_object
  label: 'Mailchimp Settings'
  mapping:
    api_key:
      type: string
      label: 'Mailchimp API Key'
    list_id:
      type: string
      label: 'Mailchimp List ID'
    data_center:
      type: string
      label: 'The last part of your MailChimp API key (i.e. us6).'
    success_msg:
      type: string
      label: 'Successful subscription'
    already_subscribed_msg:
      type: string
      label: 'Already subscribed user'
    system_failure_msg:
      type: string
      label: 'System Failure'
